### ISSUE TITLE
Hole bug in algebra mode

### ISSUE THREAD

**Issue by gumyr** [gumyr/build123d#194]
```py
from build123d import *

obj = Box(10, 20, 10)
obj -= Cylinder(3, 100) # Works

obj = Box(10, 20, 10)
obj -= CounterBoreHole(radius = 3, depth = 1, counter_bore_radius = 4, counter_bore_depth = 2) # Also works

obj = Box(10, 20, 10)
obj -= Hole(3) # Fails with this error:
```
```
Traceback (most recent call last):
  File "/home/jmcmullan/projects/wilbur/f.py", line 10, in <module>
    obj -= Hole(3) # Fails with this error:
           ^^^^^^^
  File "/home/jmcmullan/.local/lib/python3.11/site-packages/build123d/objects_part.py", line 357, in __init__
    self.hole_depth = 2 * depth if depth else 2 * context.max_dimension
                                                  ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'max_dimension'
```

**Comment by gumyr** [comment]
Fixed
