### ISSUE TITLE
No appropriate error message when BuildPart operation with no appropriate Faces

### ISSUE THREAD

**Issue by gumyr** [gumyr/build123d#71]
If the user doesn't use `BuildSketch.MakeFace` there will be no appropriate objects to transfer to BuildPart when starting with BuildLine.  This should be detected and a "Are you missing a MakeFace or MakeHull?" message generated.

**Comment by gumyr** [comment]
An generic message is now generated:
```py
from build123d import *

with BuildPart():
    with BuildSketch():
        with BuildLine():
            Polyline((0, 0), (0, 1), (1, 1), (1, 0), (0, 0))
```
```
Traceback (most recent call last):
  File "/home/roger/Documents/build123d/experiments/issue-71.py", line 6, in <module>
    Polyline((0, 0), (0, 1), (1, 1), (1, 0), (0, 0))
  File "/home/roger/Documents/build123d/src/build123d/build_common.py", line 204, in __exit__
    raise RuntimeError(
RuntimeError: sketch is None - BuildSketch didn't create anything
```
